version: '3'
services: 
  database:
    image: postgres
    container_name: postgres
    environment: 
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=online-sales"
    ports:
      - 5441:5432
    volumes:
      - pg-data:/var/lib/postgres/data
volumes:
  pg-data: